### ISSUE TITLE
Sistema de autenticação com o breeze

### ISSUE THREAD

**Issue by arthuresc** [arthuresc/bl-ecommerce#4]
# Description

Configuração das regras de negócio de usuário para o projeto Brindes de Luxo

Ela vai em todas as paginas que precisem serem moderadas

# To-do

- [ ]  Criar de acordo com o vídeo
- [ ]  Personalizar partes do dashboard e navbar
- [ ]  Criar personalização para edição dos produtos em cada um nos cards ou nas próprias paginas deles
