### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by arthuresc** [arthuresc/bl-ecommerce#8]
**Notion Tip: Se houver tempo criar a ideia que vc teve Arthur!**

# Description

A Home do projeto Brindes de Luxo

Ela vai dentro das tags padrões já criadas

# To-do

- [ ]  Bloco de imagem grande
- [ ]  Blocos menores
- [ ]  Ajustar para sempre aparecer somente 6 blocos menores
- [ ]  Ajustar para aparecer somente blocos de uma regra, seja categoria, tempo de criação (mais recentes) ou qualquer outra
- [ ]  Arrumar com o animate.css  as animações Hover e eetc...
