### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by arthuresc** [arthuresc/bl-ecommerce#9]
# Description

A Pagina de Configurações interna (Dashboard) do projeto Brindes de Luxo

Ela vai dentro das tags padrões já criadas

# To-do

- [ ]  Padronizar
- [ ]  Colocar logo da Brindes de Luxo em .svg
- [ ]  adicionar todas as rotas para os locais corretos de edição
- [ ]  tratar das permissões para os usuarios
